# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da448914aa5c044042a1f72ec32ed15dc124379c48e9f9382947d5fcea5712ab27156acac82eaa4ee8297a61e84fa1ac8070f7a9e5154f0f5f6f81c357dc3f26

test:
  secret_key_base: 2c1b9f36cb36482a53677d2b046646a63f05f4246e6526de74cee35a721b50d660dd44dcf8948d78b5123318a39a3dd3c6a8ba60894065a39309af160cad0ea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
